信息安全从业人员
* 《风险管理专业级》范围与要求

| 课程名称            | 课程类型 | 选择范围 | 所占比例 |
|---------------------+----------+----------+----------|
| 项目管理基础(II 级) | 通用课程 | 全部     |      10% |
| 信息安全技术(I 级)  | 通用课程 | 3,4,5,6  |      10% |
| 风险管理(II 级)     | 专业课程 | 全部     |      70% |
| 通信技术基础        | 附加课程 | 全部     |      10% |

* 科目考试范围
** 项目管理
*** 项目管理基本概念(2级 10%)
1. 正确理解项目的本质
项目是指一系列具有特定的目标，有着明确开始和终止日期，资金有限，消耗资源的活动和任务。项目的参数包括项目范围、质量、成本、时间、资源。
2. 正确理解管理的本质
管理就是决策，是所有人的人类组织（不论是家庭、企业或政府）都有的一种活动，这种活动由五项要素组成：计划、组织、指挥、协调、控制，管理就是实行计划、组织、指挥、协调、控制的过程。
管理四要素：管理主体、管理客体、组织目的、组织环境或条件

3. 掌握项目管理的基本分类
开发类项目管理、集成类项目管理
4. *熟练掌握* 项目管理的生命周期与流程
- 项目管理生命周期：初始阶段→实施阶段→运行阶段→结束阶段
- 初始阶段（确定需求、项目论证、项目选择）
- 实施阶段（进度安排、项目实施、项目控制）
- 运行阶段（项目执行、生产安排）
- 结束阶段（项目评估、项目总结）
- 项目管理流程：
- 制定技术目标
- 组建项目组
- 制订项目计划
- 处理范围变化
- 控制实际进展
- 整理、完善技术档案
- 形成知识网络

5. *掌握* 项目管相对其他管理的特性
   - 明确的目标：其结果只可能是一种期望的产品，也可能是一种所希望得到的服务。
   - 唯一性：每一个项目都是唯一的
   - 资源成本约束性：每一个项目都需要运用各种资源来实施，而资源是有限的
   - 项目实施的一次性：项目不可重复。
   - 项目的确定性：项目必有确定的终点，当项目目标发生实质性变动时，它就不是原来的项目了，而是一个新的项目。
   - 特定的委托人：它既是项目结果的需求者，也是项目实施的资金提供者。
   - 结果的不可逆转性：不论结果如何，项目结束，结果也就确定了。 

*** 项目管理的发展历史与现状
1. 了解项目管理的发展过程
   1)项目管理的萌芽__20世纪40年代的“曼哈顿计划”、50年代后期关键路线法(CPM)和计划评审技术(PERT)的应用以及60年代的“阿波罗”载人登月计划,虽然它们的侧重点各有不同,但其取得的巨大成功预示着项目管理已初步形成一套科学的系统方法。  
   2)项目管理理论研究的组织体系和知识体系的形成  
将项目管理作为一门科学开展系统的理论研始于20世纪60年代。创建于1965年的以欧洲为主体的国际项目管理协会(IPMA)和创建于1969年的美国项目管理学会(PMI)是项目管理的两大研究组织体系1983年,在PMI发表的一份研究报告中,项目管理的基本内容被划分为范围管理、成本管、时间管理、质量管理、人力资源管理和沟通管理等6个领域。这些领域成了PMI的项目管理专业化的基础内容。  
   3)项目管理的传播和现代化  
20世纪70~80年代项目管理迅速传遍了世界各国。从美国最初的军事项目和宇航项目管理,很快扩展到各种类型的民用项目管理。项目管理除了计划、协调和控制外,对采购、合同、进度、费用、质  
   4)项目管理的新发展  
20世纪90年代以后,为了在迅猛变化、竞争激烈的市场中,迎接经济全球化、集团化的挑战,项目管理更加注重人的因素,注重顾客,注重柔性管理,力求在变革中生存和发展。在这个阶段,应用领域进一扩大,尤其是在新兴产业中得到了迅速发展,譬如电讯、软件、信息、金融、医药等。现代项目管理的任务已不仅仅是执行项目,而且还要开发项、经营项目,以及为经营项目完成后形成的设施或其它成果准备必要的条件。

2. 了解国际项目管理的发展现状
目前国际专业人士对项目管理的重要性及其基本概念已经有了共识，各种专业性组织如学会、培训机构、咨询服务机构与开发机构等等，如雨后春笋，竞相生长，发展势头非常迅猛，当前国际项目管理的发展现状可以用3大特点、3个热点来概括：
    - 3大特点：
        1. 全球化的时代特点；
        2. 多元化的行业特点;
        3. 专业化的学科特点
    - 3个热点：
        + 证书制热；
        + 培训热；
        + 软件热
3. 了解国际国内项目管理人员认证情况
认证的主体不同。ipmp和pmp是国际认证体系，ITPMP和cpmp是中国的。权威指数（个人意见）PMP>IPMP>CPMP ，ITPMP。CPMP是劳动职业的认定，而ITPMP是专业行业认定，可比性不强。
   1. 国际项目管理人员认证情况
国际项目管理专业资质认证(International Project Management Professional，简称IPMP)是IPMA在全球推行的四级项目管理专业资质认证体系的总称。IPMP是对项目管理人员知识、经验和能力水平的综合评估证明。根据IPMP认证等级划分，获得IPMP各级项目管理认证的人员，将分别具有负责大型国际项目、大型复杂项目、一般复杂项目或具有从事项目管理专业工作的能力。
IPMA依据国际项目管理专业资质标准（IPMA Competence Baseline，简称ICB），针对项目管理人员专业水平的不同，将项目管理专业人员资质认证划分为四个等级，即A级、B级、C级、D级，每个等级分别授予不同级别的证书。
A级(Level A)证书是国际特级项目经理（Certified Projects Director）。获得这一级别认证的项目经理有能力指导一个企业或组织内的诸多复杂项目的管理，或者管理一项国际合作的复杂项目。适用于跨国企业或国内大型建筑企业集团的决策层、经理层中董事长、总经理及其管理团队中高层管理人员的资质认证。
B级(Level B)证书是国际高级项目经理（Certified Senior Project Manager）。获得这一级别认证的项目经理可以管理大型复杂项目，或者管理一项国际合作项目。适用于跨国企业或国内大型建筑企业集团的中高层管理骨干及其分（子）公司领导层、大型国际工程项目经理、国内工程总承包项目的项目经理认证。C级(Level C)证书是国际项目经理（Certified Project Manager）。获得这一级别认证的项目经理能够管理一般复杂项目，也可以在所在项目中辅助高一级别的项目经理进行管理。C级认证是应用最广泛的国际项目经理人员认证，适用于所有企业的项目经理，包括工程总承包、施工总承包、专业承包及其分项管理的项目管理人员等。
D级(Level D)证书是国际助理项目经理（Certified Project Management Associate）。获得这一级别认证的人员具备项目经理从业的基本知识，并可以将它们应用于项目管理领域，是项目管理人员的基础认证，适用于所有有志于从事项目管理的专业人员。
 由于各国项目管理发展情况不同，IPMA允许各成员国的项目管理专业组织结合本国特点，参照国际项目管理协会专业资质认证标准ICB，制定在本国认证国际项目管理专业资质的国家标准（National Competence Baseline，简称NCB）。中国国际工程项目经理【IPMP（工程）】培训与认证指导委员会（以下简称IPMP[工程]指导委员会）根据IPMA在全球推行的四级项目管理专业资质认证体系，结合中国的建设工程项目管理实际和中国项目经理的基本需求，正逐步建立具有中国特色并适应国际化发展的行业标准和培训认证体系。
   2. 国内项目管理人员认证情况
CPMP：中国项目管理师 (China Project Management Professional简称CPMP) 国家职业资格认证是中华人民共和国劳动和社会保障部在全国范围内推行的项目管理专业人员资格认证体系的总称。它分四个等级，即项目管理员、助理项目管理师、项目管理师、高级项目管理师，每个等级分别授予不同级别的证书。学员经培训并考试合格后，获得相应级别的证书。（详细知识可参考国家职业技能鉴定项目管理专家委员会中国项目管理师官方网站 http://www.cpmp.org.cn） 

ITPMP：信息系统项目管理师属于计算机技术与软件专业技术资格(水平)考试（即软考）高级资格考试里面的一项考试。计算机技术与软件专业技术资格（水平）考试（以下简称计算机软件考试）是原中国计算机软件专业技术资格和水平考试（简称软件考试）的完善与发展。这是由国家人事部(已改为：人力资源和社会保障部）和信息产业部（已改为：工业和信息化部）领导下的国家级考试，其目的是，科学、公正地对全国计算机与软件专业技术人员进行职业资格、专业技术资格认定和专业技术水平测试。





*** 九大项目管理知识领域
1. *熟练掌握* 项目综合管理,项目范围管理,项目时间管理,项目成本管理,项目质量管理,项目人力资源管理,项目沟通管理,项目风险管理和项目采购管理思想和方法.

+ 项目范围管理
是为了实现项目的目标，对项目的工作内容进行控制的管理过程。它包括范围的界定，范围的规划，范围的调整等。
+ 项目时间管理
是为了确保项目最终的按时完成的一系列管理过程。它包括具体活动界定，活动排序，时间估计，进度安排及时间控制等项工作。很多人把GTD时间管理引入其中，大幅提高工作效率。
+ 项目成本管理
是为了保证完成项目的实际成本、费用不超过预算成本、费用的管理过程。它包括资源的配置，成本、费用的预算以及费用的控制等项工作。
+ 项目质量管理
是为了确保项目达到客户所规定的质量要求所实施的一系列管理过程。它包括质量规划，质量控制和质量保证等。
+ 项目人力资源管理
是为了保证所有项目关系人的能力和积极性都得到最有效地发挥和利用所做的一系列管理措施。它包括组织的规划、团队的建设、人员的选聘和项目的班子建设等一系列工作。
+ 项目沟通管理
是为了确保项目的信息的合理收集和传输所需要实施的一系列措施，它包括沟通规划，信息传输和进度报告等。
+ 项目风险管理
涉及项目可能遇到各种不确定因素。它包括风险识别，风险量化，制订对策和风险控制等。
+ 项目采购管理
是为了从项目实施组织之外获得所需资源或服务所采取的一系列管理措施。它包括采购计划，采购与征购，资源的选择以及合同的管理等项目工作。
+ 项目集成管理
是指为确保项目各项工作能够有机地协调和配合所展开的综合性和全局性的项目管理工作和过程。它包括项目集成计划的制定，项目集成计划的实施，项目变动的总体控制等

2. *掌握* 项目综合管理,项目范围管理,项目时间管理,项目成本管理,项目质量管理,项目人力资源管理,项目沟通管理,项目风险管理和项目采购管理工具和实施技巧.

*** 开发类项目管理技巧
1. *掌握* 开发类项目管理的特点(*这是项目管理的特定，开发类的和管理类的都没有找到*)
  - 普遍性
  项目作为一种一次性和独特性的社会活动而普遍存在于我们人类社会的各项活动之中，甚至可以说是人类现有的各种物质文化成果最初都是通过项目的方式实现的，因为现有各种运营所依靠的设施与条件最初都是靠项目活动建设或开发的。
  - 目的性
  项目管理的目的性要通过开展项目管理活动去保证满足或超越项目有关各方面明确提出的项目目标或指标和满足项目有关各方未明确规定的潜在需求和追求。
  - 独特性
  项目管理的独特性是项目管理不同于一般的企业生产运营管理，也不同于常规的政府和独特的管理内容，是一种完全不同的管理活动。
  - 集成性
  项目管理的集成性是项目的管理中必须根据具体项目各要素或各专业之间的配置关系做好集成性的管理，而不能孤立地开展项目各个专业或专业的独立管理。
  - 创新性
  项目管理的创新性包括两层含义：其一是指项目管理是对于创新（项目所包含的创新之处）的管理，其二是指任何一个项目的管理都没有一成不变的模式和方法，都需要通过管理创新去实现对于具体项目的有效管理。
  
2. *掌握* 开发类项目项目生命周期



3. *正确掌握* 开发类项目九大管理知识领域特性.
4. *实践* 一个完整的开发类defrost项目实践过程.

*** 集成类项目管理技巧
1. *掌握* 集成类项目管理的特点
2. *掌握* 集成类项目生命周期
3. *掌握* 集成类项目九大管理知识领域特性
4. *实践* 一个完整的集成类项目过程

** 信息安全技术(1级 10%)
*3.信息安全技术*
1. 了解网络安全技术的范畴
　　网络安全技术指致力于解决诸如如何有效进行介入控制，以及如何保证数据传输的安全性的技术手段，主要包括物理安全分析技术，网络结构安全分析技术，系统安全分析技术，管理安全分析技术，及其它的安全服务和安全机制策略。
2. 了解网络边界划分原则与方法
    安全域是指同一环境内有相同的安全保护需求、相互信任、并具有相同的安全访问控制和边界控制策略的网络或系统。启明星辰公司采用“同构性简化”的安全域划分方法，将复杂的大网络进行简化后设计防护体系，以便进行有效的安全管理。启明星辰公司安全域划分遵循以下原则：业务保障原则； 结构简化原则；立体协防原则。

3. 了解典型的网络安全问题

4. 了解典型的网络攻击手段
   网络攻击可分为拒绝服务型DoS,攻击扫描窥探攻击和畸形报文攻击三大类.
　 - 拒绝服务型DoS, Deny of Service 攻击是使用大量的数据包攻击系统使系统无法接受正常用户的请求或者主机挂起不能提供正常的工作主要DoS攻击有SYN Flood Fraggle等,拒绝服务攻击和其他类型的攻击不大一样攻击者并不是去寻找进入内部网络的入口而是去阻止合法的用户访问资源或路由器
   - 扫描窥探攻击是利用ping扫射包括ICMP和TCP来标识网络上存活着的系统从而准确的指出潜在的目标利用TCP和UCP端口扫描就能检测出操作系统和监听着的潜在服务,攻击者通过扫描窥探就能大致了解目标系统提供的服务种类和潜在的安全漏洞为进一步侵入系统做好准备 
　- 畸形报文攻击是通过向目标系统发送有缺陷的IP报文使得目标系统在处理这样的IP包时会出现崩溃给目标系统带来损失主要的畸形报文攻击有Ping of Death Teardrop等

5. 了解网络边界防御原理与方法
   - 如何防护边界呢？
对于公开的攻击，只有防护一条路，比如对付DDOS的攻击；但对于入侵的行为，其关键是对入侵的识别，识别出来后阻断它是容易的，但怎样区分正常的业务申请与入侵者的行为呢，是边界防护的重点与难点。我们把网络与社会的安全管理做一个对比：要守住一座城，保护人民财产的安全，首先建立城墙，把城内与外界分割开来，阻断其与外界的所有联系，然后再修建几座城门，作为进出的检查关卡，监控进出的所有人员与车辆，是安全的第一种方法；为了防止入侵者的偷袭，再在外部挖出一条护城河，让敌人的行动暴露在宽阔的、可看见的空间里，为了通行，在河上架起吊桥，把路的使用主动权把握在自己的手中，控制通路的关闭时间是安全的第二种方法。对于已经悄悄混进城的“危险分子”，要在城内建立有效的安全监控体系，比如人人都有身份证、大街小巷的摄像监控网络、街道的安全联防组织，每个公民都是一名安全巡视员，顺便说一下：户籍制度、罪罚、联作等方式从老祖宗商鞅就开始在秦国使用了。只要入侵者稍有异样行为，就会被立即揪住，这是安全的第三种方法。作为网络边界的安全建设，也采用同样的思路：控制入侵者的必然通道，设置不同层面的安全关卡，建立容易控制的“贸易”缓冲区，在区域内架设安全监控体系，对于进入网络的每个人进行跟踪，审计其行为等等。 
   
- 边界防护技术: 
   - 防火墙技术;
   - 多重安全网关技术;
   - 网闸技术
   - 数据交换网技术;

6. 了解典型的网络边界防御设备的系统原理与应用方法(网关防御,网络监控,网络交换).
7. 了解网络通信安全原理与方法
8. 了解典型的网络通讯安全设备的系统原理与应用方法(访问控制,通信加密).
*4.平台安全技术*
1. 了解常用系统平台(UNIX, Linux, Windows)的典型安全问题
   1. 缓冲区溢出：在一些程序中，对预先分配的缓冲区没有做到边界检查，当正在执行的程序缓冲区越界时，就会执行非正常的操作或功能。通常，会重写堆栈中函数的返回地址，指向其他地方，然后执行一个 root shell 或一个可以改变程序保护的代码，如要求root权限等

   2. Sscan 扫描工具：Sscan 对系统进行扫描，检测主机是否存在安全漏洞，尽管它本身不进行攻击，但它可以配置成自动攻击的恶意脚本来进行攻击。所以要检查日志文件看端口是否被扫描过，以确保安全。

   3. 拒绝服务性攻击：最近几年拒绝服务性攻击明显增多，众所周知的smurf 攻击，主要是含有虚假源地址的大量ICMP包发送到一个或多个主机上，在一个能够多路广播的网络中，将导致许多主机响应每一个包，结果使整个网络充满了包，使系统忙于应付。通常，低速上网的用户进入到位于高速网络中的主机，安装攻击性工具，并从这台主机上发动攻击

2. 了解常用的应用支撑平台(WEB, 数据库等)的典型的安全问题.

   WEB: (OWASP)通过调查，列出了对Web应用的危害较大的安全问题，主要包括：未验证参数，访问控制缺陷，账户及会话管理缺陷，跨站脚本漏洞，缓冲区溢出，命令注入漏洞，错误处理问题，远程管理漏洞，Web服务器及应用服务器配置不当。
数据库: 
   
   1. 不安全的Web应用程序
      尽管OWASP等组织在过去几年中积极传播最佳的安全编程方法，但事实是互联网中仍然存在数百万存在漏洞的Web应用程序，这些应用程序将用户引导到哪里？当然是到后端数据库。Accuvant LABS首席安全架构师，同时也是著名数据库安全研究人员David Litchfield表示，缩小漏洞差距的进展非常缓慢。Litchfield表示：“这相当令人沮丧，尤其是看到几年前开始使用的相同工具包到现在仍然能够很好地用于渗透测试时。最糟糕的部分就是开发人员仍然开发出存在以前相同错误的新应用程序，例如，无法验证输入。”他表示，高等教育机构仍然没有教授学生多年前开发出来的安全编程原则，你以为这些从大学毕业的开发人员会知道这些基本知识，但是其实他们并没有学过。

    2. 泛滥的数据库系统特权账户
       即使是在整个IT基础设施部署了高效身份和访问管理工具和程序的企业，数据库往往都处于无人看管的状况。“企业经常忘记将数据库用户的身份生命周期管理绑定到他们的IAM核心中，尤其是共享账户和服务账户，”Identropy首席架构师Nishant Kaushik表示，“数据库访问必须与配置、强大的身份验证和特权账户管理工具配合工作。”
       但事实上，IT部门往往允许开发人员和其他IT系统管理员通过几乎无限制权限的系统账户来进入数据库。这些账户经常在访问控制或监控系统的控制之外被使用，并且很容易被内部人员滥用或者被外部攻击人员用于发动数据库攻击。
    3. 错误配置的网络分段
　　　安全最佳做法和法规都大肆吹捧网络分段是控制风险范围以保护高价值数据库资产的重要方式。但是如果配置不当的话，尤其是在防火墙的规则集中，这些网络分段的安全漏洞都可能让数据库泄露。安全咨询公司Principle Logic公司的创始人Kevin Beaver花了大部分时间在为客户执行网络安全和web应用程序安全评估的工作上。他的评估结果经常显示企业在分段网络时糟糕的工作情况。


3. 了解各类安全漏洞的管理标准与方法.
4. 了解典型的对平台攻击手段.
5. 了解主机安全防护的主要手段(安全加固, 安全监控, 安全审计, 主机保护等)的原理与实施方法及其工具.
6. 了解桌面系统的典型安全问题
7. 了解桌面系统的安全保障的方法与工具.

*5.应用安全技术*
1. 了解各类常用应用系统(通用应用系统,专业应用系统,特殊业务系统等)的典型安全问题.
2. 了解安全软件开发过程管理与控制.
3. 了解典型的应用安全漏洞
4. 了解应用软件安全测试方法与工具.

*6.数据安全技术*
1. 了解数据安全的范畴
　　数据安全有对立的两方面的含义：一是数据本身的安全，主要是指采用现代密码算法对数据进行主动保护，如数据保密、数据完整性、双向强身份认证等，二是数据防护的安全，主要是采用现代信息存储手段对数据进行主动防护，如通过磁盘阵列、数据备份、异地容灾等手段保证数据的安全，数据安全是一种主动的包含措施，数据本身的安全必须基于可靠的加密算法与安全体系，主要是有对称算法与公开密钥密码体系两种。
2. 了解数据生命周期的各阶段安全需求
3. 了解数据生命周期的各阶段安全保障技术与方法.
　　1. 数据创建阶段
     随着信息技术的不断发展和普及，所产生的数据需要存储环境以利于及时的处理、管理和保护。因而需要稳定、可其实我不想说的、高可扩展能力的存储设备。不同的应用和数据，需要不同容量、功能和价格的存储系统，以满足合理的成本和投资回报。数据的价值通常会随着时间逐渐降低，因此所有数据在创建时都应当获得一个由数据的类型、数据的价值和相关法规的要求决定的删除曰期。系统将定期清除到期的数据。除非对过期数据的创建进行正确的控制，否则对相关数据的搜索将会导致运营效率的不断降低。信息生命周期管理就是要根据应用的要求，数据提供的时间及数据和信息服务的等级，提供相适应的数据产生，存储，管理等条件，以保障数据的及时供应。
    2. 数据保护阶段
       今天很多企业的经济效益都与信息的连续可用性、完整性和安全性息息相关。随着越来越多的信息以数字化的格式出现，企业面临着如何以相同或者更少的资源管理迅速增长的信息和存储的挑战。同时，企业的各项业务需要找到和获取所需要的信息.信息可用性的降低，或者信息的丢失，对企业而言,都意味着时间的浪费,生产率的降低或灾难。从电子数据处理产生以来，对于数据保护的需求一直没有发生变化：需要防止数据受到无意或者有意的破坏。最近发生的一系列事件使得数据保护和灾难恢复问题成为了人们关注的焦点，越来越多的组织都意识到从他们的数据中心所遭受的重大损失中恢复所需要的努力和时间，以及制定相应计划的重要性。这个解决方案是一系列技术和流程的组合：备份、远程复制和其他数据保护技术。它们需要与一组流程和步骤组合，确保及时的恢复。当前,很多需要大量存储的应用，尤其是电子商务、CRM和ERP等，都需要24×7的运作和在线。系统的可用性在一定的程度上取决于数据的可用性：即使在技术上服务器和网络都是可用的,但是如果应用系统不能访问到正确的数据，用户将认为它是不可用。在此情况下,即便是事先安排的停机（“备份时间”,”升级时间”等）也是无法接受的。企业已经对很多可以帮助他们减少计划性停机和意外停机的技术投入了大量的资金,例如实时数据复制技术，计算机群集系统，以及远程数据复制技术等。信息生命周期管理将按照数据和应用系统的等级，采用不同的数据保护措施和技术，以保证各类数据和信息得到及时的和有效的保护。

     3. 数据访问阶段
        信息生命周期管理的主要目标是确保信息可以支持业务决策和为企业提供长期的价值。因此，信息必须便于访问，最好可以在一个企业的多个业务环节和业务应用之间共享，以提供最大限度的业务价值。此外，信息必须可以支持多种业务流程,因此这个阶段将成为信息生命周期管理与业务流程管理的交叉点。成功的数据访问和管理是通过深入地了解数据在企业中扮演的重要角色而实现的。要做到这一点，首先要问：“这些数据的真正价值是什么？”换句话说，它对于业务的成功运行具有什么重要意义？这可以帮助企业在制定一项数据存储战略时集中精力。
    
     4. 数据迁移阶段
       	信息技术发展是如此快速，以至信息技术的设备在比较短的时期内就要实现一定程度上的更新。在当前信息应用的环境中，保持应用系统的全天候运作已是必须条件。即使是事先计划的、为了对系统进行升级或对系统配置改变而进行的停机对许多客户来说也是无法接受的事件。因此，越来越多的变动必须在运行系统上进行。数据迁移就是其中一个事例：将数据从一个存储设备转移到另外一个存储设备，而且不影响系统的正常运行。过去，企业通常需要手动地将数据迁移到新的存储系统。其过程复杂而且影响业务的正常运作.而信息生命周期管理(ILM)考虑到了这类的需求,采用必要的技术加以配合,使数据的迁移简单,自动化而且不影响业务的运作。


      5. 数据归档阶段
         维持一个数据备份和归档系统可以从多个方面支持企业的业务运作。它可以提供交易和决策记录，以及关于决策时的周边环境的所有信息。它可以防止这些记录被无意破坏。它能确保那些仍然对于一个组织具有一定作用的数据可以得到妥善的保存，即使在它不再具有立即的相关性（例如用作参考的数据）。可以从生产系统中清除使用率很低的数据，降低总拥有成本。企业已经意识到备份其数据的重要性。这些数据让企业可以在原始信息因为某种原因被损坏或破坏时进行恢复。数据备份是企业数据存储战略的重要组成部分.由于对备份数据访问的频率和速度要求不是很高,因而,价格低,容量大的存储介质和系统成为最佳选择。

       6. 数据回收(销毁)阶段
          许多数据总会在一段时期后，没有再继续保存的价值。这时，企业必须要制定相关的政策，对没有保留或保存必要的数据进行销毁或回收.被销毁或回收的数据将从活动和非活动系统，以及数据仓库等系统中清除。对一些数据，不能轻率地进行销毁你知道我想做什么吗？作。企业必须确保其销毁的数据不会与企业和政府的条例和法规相违背,对企业正在进行的诉讼案子或者其他政策无关。企业应当建立科学的和明确的数据回收(销毁)规则。

4. 了解灾难备份与恢复技术
   *主要的灾难备份技术介绍*   
       1. 基于磁带的备份技术
          利用磁带拷贝进行数据备份和恢复是常见的传统灾难备份方式。这种方式的特点是利用盘式磁带或盒式磁带存储数据，然后将存储设备置于较远的安全地带。基于磁带的备份技术，比较传统和常见，在灾难或者故障发生时，要将磁带去除，运输到灾难发生的地点，进行灾难恢复工作。这些磁带拷贝通常都是按一定的周期天、周或月进行组合保存的。磁带是顺序读取的，且读取速度慢，适合于对时间不敏感的资料备份。所以，由于难以支持实时业务，属于典型的传统灾难备份方式。
       2. 基于应用软件的数据容灾备份
         通过应用软件来进行数据的远程拷贝和同步操作，在主操作中心发生冲突时，容灾备份中心可以借助应用软件来恢复操作，或者接管主操作中心的任务，这种技术是基于应用软件的数据容灾备份。它的实现是依靠应用软件本身的两个异地数据处理库将每次的数据信息分别写入主操作中心和备份中心的数据存储库中。这种方式实现起来比较复杂，要求应用软件系统的I/O通信接口足够大，利用应用软件来实现数据拷贝和数据同步。这样的话会对整个系统的带来较大的影响，恢复起来的难度也很大。
   
       3. 远程数据库备份
        要实现远程数据库备份需要进行远程拷贝和信息同步，这就要借助数据库系统软件来操作。基于数据库的拷贝形式有多种，可以是实时拷贝、定时拷贝和一定操作时拷贝。此外，要保持数据的一致性不受到干扰还要求这种方式中有自动检测冲突和解决的措施。实际上，实现远程数据拷贝主要是解决主操作系统与存储系统之间的数据同步，也就是说把主操作系统的操作实时或定时拷贝到存储（备用）系统数据库中去，以实现两种系统间数据的一致性。这种备份方式的效率会受数据库软件性能、网络带宽、服务器性能等一系列因素影响，适用于对数据一致性要求较高、数据更新较频繁的应用。

       4. 基于主机逻辑磁盘卷的远程备份
          逻辑磁盘卷的概念通俗的解释是在物理存储器与操作系统间添加的逻辑存储管理层。基于主机逻辑磁盘卷的远程备份是按照需求，把一个或者多个逻辑管理层远程拷贝以备份。通过软件可以实现这个远程备份方案，需要软件中具备逻辑卷管理模块和远程备份控制模块。实现两个逻辑卷之间数据同步的过程需要借助这个远程备份控制管理软件。软件通过实时备份，将主节点存储器上的卷信息每次I/O数据同步到远程节点的管理层，实现数据同步或准同步。主机节点与远程节点需要配置带宽相等的坤通道来适应主机的处理性能要求。具体操作时，可以按照数据的更换速度、通信状况等因素，把远程备份设为同步、准同步或者定期同步等方式以应对不同的状况。当主机性能和通信带宽的要求得到满足时，其效率和数据一致性就得到了保证。

       5. 基于SAN的备份技术
          SAN(Storage Area Network) 存储域网是在主机和存储器之间建设的存储网络设备，是一个通信接口，可以将主机的操作信息传递给存储器的同时把操作信息记录并完成远程拷贝。SAN可以将各模块的功能拆解，并集中处理信息，在服务器与存储器之间任意连接。SAN可提高系统的灵活性和数据的安全性。SAN代表的是未来灾难备份技术的发展方向，是以数据存储为中心，网络拓扑结构表现为可伸缩性，其光通道连接方式具有较高的速率，可提供SAN内部任意节点之间的多路可选择的数据交换，并且将数据存储管理集中在相对独立的存储区域网内。在SAN环境中，以光纤连接设备(光纤通道交换机等)为中心，连接主机逻辑磁盘卷的概念通俗的解释是在物理存储器与操作系统间添加的逻辑存储管理层。基于主机逻辑磁盘卷的远程备份是按照需求，把一个或者多个逻辑管理层远程拷贝以备份。通过软件可以实现这个远程备份方案，需逻辑磁盘卷的概念通俗的解释是在物理存储器与操作系统间添加的逻辑存储管理层。基于主机逻辑磁盘卷的远程备份是按照需求，把一个或者多个逻辑管理层远程拷贝以备份。通过软件可以实现这个远程备份方案，需要软件中具备逻辑卷管理模块和远程备份控制模块。实现两个逻辑卷之间数据同步的过程需要借助这个远程备份控制管理软件。软件通过实时备份，将主节点存储器上的卷信息每次I/O数据同步到远程节点的管理层，实现数据同步或准同步。主机节点与远程节点需要配置带宽相等的坤通道来适应主机的处理性能要求。具体操作时，可以按照数据的更换速度、通信状况等因素，把远程备份设为同步、准同步或者定期同步等方式以应对不同的状况。当主机性能和通信带宽的要求得到满足时，其效率和数据一致性就得到了保证。
          要软件中具备逻辑卷管理模块和远程备份控制逻辑磁盘卷的概念通俗的解释是在物理存储器与操作系统间添加的逻辑存储管理层。基于主机逻辑磁盘卷的远程备份是按照需求，把一个或者多个逻辑管理层远程拷贝以备份。通过软件可以实现这个远程备份方案，需要软件中具备逻辑卷管理模块和远程备份控制模块。实现两个逻辑卷之间数据同步的过程需要借助这个远程备份控制管理软件。软件通过实时备份，将主节点存储器上的卷信息每次I/O数据同步到远程节点的管理层，实现数据同步或准同步。主机节点与远程节点需要配置带宽相等的坤通道来适应主机的处理性能要求。具体操作时，可以按照数据的更换速度、通信状况等因素，把远程备份设为同步、准同步或者定期同步等方式以应对不同的状况。当主机性能和通信带宽的要求得到满足时，其效率和数据一致性就得到了保证。
           模块。实现两个逻辑卷之间数据同步的过程需要借助这个远程备份控制管理软件。软件通过实时备份，将主节点存储器上的卷信息每次I/O数据同步到远程节点的管理层，实现数据同步或准同步。主机节点与远程节点需要配置带宽相等的坤通道来适应主机的处理性能要求。具体操作时，可以按照数据的更换速度、通信状况等因素，把远程备份设为同步、准同步或者定期同步等方式以应对不同的状况。当主机性能和通信带宽的要求得到满足时，其效率和数据一致性就得到了保证。、磁盘阵列、磁带库等多种设备，环境比较复杂。在多种光通道传输协议逐渐走向标准化并且跨平台群集文件系统投入使用后，SAN最终将实现在多种操作系统下最大限度的数据共享和数据优化管理，以及系统的无缝扩充。 

    *灾难备份数据复制方案*
       1. 基于存储的数据复制方案
          基于存储的数据复制技术核心是通过磁盘阵列内建的固件或微操作系统，利用IP网络、DWDM、光纤通道等传输网络，将数据以同步或异步的方式复制到远端灾备中心
 数据复制过程完全在磁盘阵列间实现，使得数据与上层应用软件隔离，因此对服务器的影响非常小。此外，由于运行机制是利用镜像来复制数据，并借高速缓存加速I/O读写速度，因此业务中心、灾备中心两端的数据差异时间非常小，加上存储系统本身具有一定的容错能力，因此具有较高的性能和稳定性。
           总结：该方案的优点是成熟、稳定、快速、高效，对服务器处理能力的影响小。在金融、证券、电信、政府、石油等行业有广泛的应用案例。  该方案的缺点是对灾备中心的存储空间需求较大，数据复制过程对带宽的要求高，支持同构存储平台，只能单向复制。但是随着存储技术的发展，各专业存储设备厂商为数据复制灾难备份提供了基于NAS、SAN等各种存储技术的专用存储设备，它能帮助用户建立集中的存储中心，并通过专用设备所提供的各种同步镜像或异步镜像等技术，实现更加灵活的数据复制灾难备份方案。 
        2. 基于数据库的数据复制技术
           基于数据库的数据复制方案是数据库特有的灾难备份/恢复技术，利用了数据库系统的日志备份和恢复机制。此方式需要在源数据库（业务中心）及目标数据库（灾备中心）的数据库服务器上各安装一套Agent（代理程序），由Agent定时分析抽取Oracle数据库中实时增量数据，并将这些增量传送到灾备中心上，如图3所示。 
　　     定时的增量数据经过优化，放入传输队列中等待传输，Agent对整个传输、装载过程进行监控，如果此阶段出现错误会及时提示用户解决问题。
          在数据复制过程中，目标数据始终处于打开状态，如果源数据库系统（业务中心）发生灾难，整个恢复时间只是用来准备的时间。而且在没有接管业务中心数据库系统的情况下，灾备中心的数据库还可以用来支持OLP应用、报表和查询。
          总结：该方案的优点是服务器、操作系统、数据库版本可以异构（分别来自不同厂家），组网方式灵活，数据传输过程对带宽的要求不高；灾备中心的数据库始终保持在启用状态，确保灾难恢复时数据可用。
          该方案的缺点是复制软件占用主机资源，仅适用于数据库环境，无法处理文件、目录等非常结构化数据，具有一定的局限性；维护复杂度高，需要应用系统比较熟悉的人员才能维护，多见于应用软件自行维护的用户，灾难恢复的时间较基于存储的数据复制技术时间长。

** 风险管理(2级 70%)
***** 1.风险管理的业界标准与实践
1. 理解GB/T 24353
   1.1 风险管理原则
   - 控制损失,创造价值
   - 融入组织管理过程
   - 支持决策过程
   - 应用系统的,结构化的方法
   - 以信息为基础
   - 环境依赖
   - 广泛参与,充分沟通
   - 持续改进
   1.2 风险管理过程
   - 明确环境信息
      1.外部环境信息
      2.内部环境信息
      3.确定风险准则
   - 风险评估（风险识别、风险分析、风险评价）
   - 风险应对（选择风险应对措施、制定风险应对计划）
   - 监督和检查
   - 沟通与记录

   1.3 风险管理实施--风险管理体系的要素
   - 风险管理方针--应明确的事项  
      1.组织的风险管理理念
      2.组织的最高管理者对风险管理的承诺
      3.组织的风险管理目标
      4.组织的风险偏好
      5.风险管理方针与组织的目标及其他方针之间的关系
      6.风险管理的职责分配
      7.风险管理的程序和方法
      8.风险管理的资源配置
      9.测量和报告风险管理绩效的方式
      10.建立风险管理体系的计划
      11.继续改进的承诺
   - 适当的制度和程序，是风险管理嵌入到组织的所有活动和过程中
   - 与组织结构相关的职责，及有关的与组织的绩效指标一致的风险管理绩效指标
   - 资源分配
   - 与所有利益相关者沟通风险管理的机制
   - 技术手段、方法、工具等

2. 理解GB/T 20984
   2.1 *术语与定义*
     1. 资产（asset）：对组织具有价值的信息与资源，是安全策略保护的对对象
     2. 资产价值（asset alue）：资产的重要程度或敏感程度的表征。资产价值是资产的属性，也是进行资产识别的主要内容
     3. 可用性（availability）：数据或资源的特性，被授权实体按要求能访问和使用数据或资源
     4. 业务战略（business strategy）：组织为实现其发展目标二制定的一组规则或要求
     5. 保密性（confidentiality）：数据所具有的特性，即表示数据所达到的未提供或未泄露给非授权的个人、过程或其他实体的程度
     6. 信息安全风险（information security risk）：人为或自然的威胁利用系统及其管理体系中存在脆弱性导致安全事件的发生及其对组织造成的影响
     7. 风险评估（risk assessment）：依据有关信息安全技术与管理标准，对信息系统及由其处理、传输和存储的信息的保密性、完整性和可用性等安全属性进行评价的过程。
     8. 信息系统 （information system）：由计算机及其相关的配套的设备、设施（含网络）构成的，按照一定的应用目标和规则对信息进行采集、加工、存储、传输、检索等处理的人机系统
     9. 检查评估（inspection assessment）：有被评估组织的上级主管机关或业务主管机关发起的，依据国家有关法规与标准，对信息系统及其管理进行的具有强制性的检查活动
     10. 完整性（integrity）：保证信息及信息系统不会被非授权更改或破坏的特性，包括数据完整性和系统完整性
     11. 组织（organization）:由作用不同的个体为实施共同的业务目标二建立的结构。一个单位是一个组合，某个业务员部门也是一个组织。
     12. 残余风险（residual risk）：采取了安全措施后，信息系统仍然可能存在的风险
     13. 自评估（self-assessment）：有组织自身发起，依据国家有关法规与标准，对信息系统及其管理进行的风险评估活动。
     14. 安全事件（security incident）：系统、服务或网络的一种课识别状态的发生，它可能是对信息安全策略的违反或防护措施的失效，或未预知的不安全状态
     15. 安全措施（security measure）：保护资产、抵御威胁、减少脆弱性、降低安全事件的影响，以及打击信息犯罪而实施的各种实践、规程和机制
     16. 安全需求（security requirement）：为保证组织业务战略的正常运作二在安全措施方面提出的要求
     17. 威胁（threat）：可能导致对系统或组织危害的不希望事故潜在起因
     18. 脆弱性（vulnerability）：可能被威胁所利用的资产或若干资产的薄弱环节
   2.2 风险评估框架及流程
     - 风险要素关系(方框代表为风险评估的基本要素,椭圆为与这些要素相关的属性)
file:2.png
https://github.com/gttiankai/Blog/blob/master/Android/2.png

file:3.png
https://github.com/gttiankai/Blog/blob/master/Android/3.png



     - 风险分析原理（涉及资产、威胁、脆弱性三个基本要素）
        - 风险分析主要内容： 
           1. 对资产进行识别，并对资产的价值进行赋值
           2. 对威胁进行识别，描述威胁的属性，并对威胁出现的频率赋值
           3. 对脆弱性进行识别，并对具体资产的脆弱性的严重程度赋值
           4. 根据威胁及威胁利用脆弱性的难以程度判断安全事件发生的可能性
           5. 根据脆弱性的严重程度及安全事件所作用的资产的价值计算安全事件造成的损失
           6. 根据安全事件发生的可能性以及安全事件出现后的损失，计算安全事件一旦发生对组织的影响，即风险值
file:4.png
https://github.com/gttiankai/Blog/blob/master/Android/4.png


      - 实施流程

file:5.png
https://github.com/gttiankai/Blog/blob/master/Android/5.png
 
   2.3 风险评估实施
      1. 风险评估准备
        - 确定目标
        - 确定范围
        - 组建团队
        - 系统调研
        - 确定依据
        - 制定方案
        - 获得支持 
      2. 资产识别
        - 资产分类
        - 资产赋值
          1. 保密性赋值：五个等级（很高、高、中等、低、很低）
          2. 完整性赋值：五个等级
          3. 可用性赋值：五个等级
          4. 资产重要性等级：五个等级
       3. 威胁识别
        - 威胁分类(在分类前应考虑威胁的来源: 环境因素,人为因素)
       4. 威胁赋值表

         | 5 | 很高 | 出现的频率很高（或大于等于 1次/周） |
         | 4 | 高   | 出现的频率较高（或大于等于 1次/月） |
         | 3 | 中等 | 出现的频率中等（或大于 1 此/年）    |
         | 2 | 低   | 出现的频率较小                      |
         | 1 | 很低 | 威胁几乎不可能发生                  |

       5. 脆弱性分析
        - 脆弱性识别内容
        - 脆弱性赋值(5个等级)
       6. 风险分析
        - 风险计算原理
            - 风险值=R（A，T，V）= R（L（T，V），F（Ia，Va）），其中,R表示安全风险计算函数，A表示资产，L表示威胁利用资产的脆弱性导致安全事件的可能性；F表示安全事件发生后造成的损失。
            - 安全事件的可能性=L（威胁出现频率，脆弱性）=L（T，V）
            - 安全事件造成的损失=F（资产价值，脆弱性严重程度）=F（Ia，Va）
         - 风险结果判定（五个等级）
         - 风险处理计划
         - 残余风险评估
       7. 风险评估文档记录
         - 风险评估文档记录的要求  
            1. 确保文档发布前是得到批准的
            2. 确保文档的更改和现行修订状态是可识别的
            3. 确保文档的分发得到适当的控制，并确保在使用时可获得有关版本的适用文档
            4. 防止作废文档的非预期使用，若因任何目的需保留作废文档时，应对这些文档进行适当的标识
         - 风险评估文档
            1. 风险评估方案
            2. 风险评估程序 
            3. 资产识别清单
            4. 重要资产清单
            5. 威胁列表
            6. 脆弱性列表
            7. 已有安全措施确认表
            8. 风险评估报告
            9. 风险处理计划
            10. 风险评估记录

2.4 信息系统生命周期各阶段的风险评估

   - 规划阶段的风险评估
   - 设计阶段的风险评估
   - 实施阶段的风险评估
   - 运行维护阶段的风险评估
   - 废弃阶段的风险评估

2.5 风险评估的工作形式

   - 自评估
       - 概念：是指信息系统拥有、运行或使用单位发起的对本单位信息系统进行的风险评估
   - 检查评估
       - 概念：是指信息系统上级管理部门组织的或国家有关智能部门依法展开的风险评
       - 检查评估也可在子评估实施的基础上，对关键环节或重点内容实施抽样评估，包括以下内容（但不仅限于）
           1. 自评估队伍及技术人员审查
           2. 自评估方法的检查
           3. 自评估过程控制与文档记录检查
           4. 自评估资产列表审查
           5. 自评估威胁列表审查
           6. 自评估脆弱性列表审查
           7. 现有安全措施有效性检查
           8. 自评估结果审查与采取相应措施的跟踪检查
           9. 自评估技术技能限制未完成项目的检查评估
           10. 上级关注或要求的关键环节和重点内容的检查评估
           11. 软硬件维护制度及实施管理的检查
           12. 突发事件应对措施的检查
       
3. 了解各行业的信息安全风险管理指引


***** 2.风险管理的实施过程
1. 了解风险管理的全过程(4个步骤)
  - 明确环境信息：明确风险管理目标，确定与组织相关的内部和外部参数，并设定风险管理的范围和有关风险准则。
  - 风险评估：包括风险识别、风险分析与风险评价。
  - 风险应对：选择并执行一种或多种改变风险的措施，包括改变风险事件发生的可能性和后果。递进的循环过程。
  - 监督和检查：定期对风险与控制进行监督和检查。
  - 沟通和记录：成功的风险评估依赖于与利益相关方的有效沟通和协商。

2. 了解风险管理准备工作(如组织与规划) 的主要方法 
规划阶段是要明确安全建设的目的,对安全建设目标实现的可能行进行分析病设计出总体方案.为了保证这些工作的完成,需要对每个工作任务中可以减少安全风险的还价或可能引入安全风险的换件进行安全风险管理.通过在项目规划阶段的风险管理来江都在项目后期处理相同安全封信啊所带来的高额成本.



3. 了解风险评估主要方法与实施 
  风险评估主要 *方法* 如下所示:
  - 故障树分析法 
     1) 建造故障树
     2) 对故障树进行简化
     3) 定性分析  
     4) 定量分析
  - 故障模式影响及危害分析法(FMECA)

  - 危害及可操作行分析法(HazOp)

  - 事件树分析法(ETA)

  - 原因-结果分析法(CCA)

  - 风险模式影响及危害分析法(RMECA)

  - 风险评审技术(VERT)

  - 概率风险评估(PRA)&动态概率风险评估(DPRA)

  - 层次分析法(AHP)
     1) 建立递阶层次结构模型
     2) 构造判断矩阵
     3) 层次单排序及一致性检验
     4) 层次总排序及一致性检验
   

*实施* 
   - 风险评估准备
   - 资产识别
   - 威胁识别
   - 脆弱性识别
   - 风险分析
   - 风险评估文档记录
具体如下图所示: 


#+CAPTION: 
file:1.jpg


https://github.com/gttiankai/Blog/blob/master/Android/1.png


4. 了解风险评估的报告格式与形成报告的方法 
*形成报告的方法* 
   1. 确保文档发布前是得到批准的
   2. 确保文档的更改和现行修订状态是可识别的
   3. 确保文档的发布得到适当的控制，并确保在使用时可获得有关版本的适用文档
   4. 防止作废文档的非预期使用，若因任何目的需保留作废文档时，应对这些文档进行适当的标识
    5. 规定其标识、存储、保护、检索、保存期限以及处置所需的控制
    6. 组织的管理者决定是否需要相关文档以及详略程度

*格式*
    1. 风险评估方案：阐述风险评估的目标、范围、人员、评估方法、评估结果的形式和实施进度等。
    2. 风险评估程序：明确评估的目的、职责、过程、相关的文档要求，以及实施本次评估所需要的各种资产、威胁、脆弱性识别和判断依据。
    3. 资产识别清单。
    4. 重要资产清单。
    5. 威胁列表：包括威胁名称、种类、来源、动机及出现的频率等。
    6. 脆弱性列表：包括脆弱性的名称、描述、类型及严重程度。
    7. 已有安全措施确认表:根据对已采取的安全措施去人的结果,形成已有安全措施确认表,包括已有安全措施名称,类型,功能描述及实施效果.
    8. 风险评估报告:对整个风险评估过程和结果进行总结,详细说明被评估对象,风险评估方法,资产,威胁,脆弱性的识别结果,风险分析,风险统计和结论等内容.
    9. 风险处理计划:对评估结果总不可接受的风险制定风险处理计划,选择适当的控制目标及安全措施,明确责任,进度,资源,并通过对残余风险的评价以确定所选择安全措施的有效性.
    10. 风险评估记录:根据风险评估程序,要求风险评估过程中的各种现场记录课复现评估过程,并作为产生歧义后解决问题的依据.


5. 了解风险处置主要方法与实施 
对不可接受的风险应根据导致该风险的脆弱性制定风险处理计划。风险处理计划中应明确采取的弥补脆弱性的安全措施、预期效果、实施条件、进度安排、责任部门等。安全措施的选择应从管理与技术两个方面考虑，安全措施的选择与实施应参考信息安全的相关标准进行。


*实施:*

风险应对措施的制定和评估时一个递进的过程，对于风险应对措施，应评估其剩余风险是否可以承受。如果剩余风险不可承受，应调整或制定新的风险应对措施，并评估新的风险应对措施的效果，直到剩余风险可以承受。执行风险应对措施会引起组织风险的改变，需要跟踪、监督风险应对的效果和有关环境信息，并对变化的风险进行评估，必要时重新制订风险应对措施。风险应对措施可包含以下几项：
  1. 决定停止或退出可能导致风险的活动以及规避风险
  2. 增加风险或承担新的风险以寻求机会
  3. 消除具有负面影响的风险源
  4. 改变风险事件发生的可能性的大小及其分布的性质
  5. 改变风险事件发生的可能后果
  6. 转移风险
  7. 分担风险
  8. 保留风险等

***** 3.风险管理工具使用*
1. 了解典型的风险管理工具(技术,管理两类工具)
   1. 技术(具体内容见page35 <<信息安全风险评估教程>>)
     - 脆弱点评估工具(漏洞扫描工具)
     - 渗透性测试工具 
   2. 管理型信息安全风险评估工具主要分为三类(具体内容见page30,<<信息安全风险评估教程>>)

     - 基于国家和政府颁布的信息安全管理标准或指南的风险评估工具,如CRAMM,RA/SYS
     - 基于专家系统的风险评估工具,如COBRA,@RISK,BDSS
     - 基于定性和定量算法的风险评估工具,如CONTROL-IT,JANBER(定性). @RISK,BDSS, RISKWATCH(定性与定量结合)

***** 4.典型风险处理措施
1. 了解典型的风险管理具体的处理措施.
   1. 明确环境信息：明确风险管理目标，确定与组织相关的内部和外部参数，并设定风险管理的范围和有关风险准则。
   2. 风险评估：包括风险识别、风险分析与风险评价。
   3. 风险应对：选择并执行一种或多种改变风险的措施，包括改变风险事件发生的可能性和后果。递进的循环过程。
   4. 监督和检查：定期对风险与控制进行监督和检查。
   5. 沟通和记录：成功的风险评估依赖于与利益相关方的有效沟通和协商。
如下图所示:
https://github.com/gttiankai/Blog/blob/master/Android/picture2.png

***** 5.风险管理实例*
1. 了解主要行业的典型安全风险特性.


2. 了解1-2个行业的典型风险管理实例.

在<<信息安全风险评估教程>>这本书的page114,有信息安全 *风险评估* 案例,题目要求的是 *风险管理* 案例,风险管理的案例暂时没有找到,后续会再找一下,若实在找不到就先使用这个.

** 通信技术基础(10%) 
***** 1.通信的基本概念*
1.理解通信的本质含义及电信概念
  通信(communication)是指按照达成的协议,信息在 人、地点、进程和机器中间进行的传送。
  电信（telecommunication）则指在线缆上或经由大气，利用电信信号或光学信号发送和 接收任何类型信息（数据、图形、图像和声音）的通信方式。
2.理解通信网络形成过程
  - 以单计算机为中心的联机终端系统
    计算机网络主要是计算机技术和信息技术相结合的产物,它从20世纪50年代起步至今已经有50多年的发展历程,在20世纪50年代以前,因为计算机主机相当昂贵,而通信线路和通信设备相对便宜,为了共享计算机主机资源和进行信息的综合处理,形成了第一代的以单主机为中心的联机终端系统. 
    在第一代计算机网络中,因为所有的终端共享主机资源,因此终端到主机都单独占一条线路,所以使得线路利用率低,而且因为主机既要负责通信又要负责数据处理,因此主机的效率低,而且这种网络组织形式是集中控制形式,所以可靠性较低,如果主机出问题,所有终端都被迫停止工作.面对这样的情况,当时人们提出这样的改进方法,就是在远程终端聚集的地方设置一个终端集中器,把所有的终端聚集到终端集中器,而且终端到集中器之间是低速线路,而终端到主机是高速线路,这样使得主机只要负责数据处理而不要负责通信工作,大大提高了主机的利用率.
    
  - 以通信子网为中心的主机互联
    随着计算机网络技术的发展,到20世纪60年代中期,计算机网络不再局限于单计算机网络,许多单计算机网络相互连接形成了有多个单主机系统相连接的计算机网络, 
    这样连接起来的计算机网络体系有两个特点: 
    ①多个终端联机系统互联，形成了多主机互联网络 
    ②网络结构体系由主机到终端变为主机到主机 
    后来这样的计算机网络体系在慢慢演变,向两种形式演变,第一种就是把主机的通信任务从主机中分离出来,由专门的CCP(通信控制处理机)来完成,CCP组成了一个单独的网络体系,我们称它为通信子网,而在通信子网连基础上接起来的计算机主机和终端则形成了资源子网,导致两层结构体现出现.第二种就是通信子网逐规模渐扩大成为社会公用的计算机网络,原来的CCP成为了公共数据通用网.

   - 计算机网络体系结构标准化 
     随着计算机网络技术的飞速发展,计算机网络的逐渐普及,各种计算机网络怎么连接起来就显得相当的复杂,因此需要把计算机网络形成一个统一的标准,使之更好的连接,因为网络体系结构标准化就显得相当重要,在这样的背景下形成了体系结构标准化的计算机网络. 
     为什么要使计算机结构标准化呢,有两个原因,第一个就是因为为了使不同设备之间的兼容性和互操作性更加紧密.第二个就是因为体系结构标准化是为了更好的实现计算机网络的资源共享,所以计算机网络体系结构标准化具有相当重要的作用.
3.了解通信网络结构
   1. 物理层：这是整个OSI参考模型的最低层，它的任务就是提供网络的物理连接。所以，物理层是建立在物理介质上（而不是逻辑上的协议和会话），它提供的是机械和电气接口。主要包括电缆、物理端口和附属设备，如双绞线、同轴电缆、接线设备（如网卡等）、串口和并口等在网络中都是工作在这个层次的。 物理层提供的服务包括：物理连接、物理服务数据单元顺序化（接收物理实体收到的比特顺序，与发送物理实体所发送的比特顺序相同）和数据电路标识。注:双绞线：是由两条相互绝缘的导线按照一定的规格互相缠绕（一般以顺时针缠绕）在一起而制成的一种通用配线，属于信息通信网络传输介质。双绞线过去主要是用来传输模拟信号的，但现在同样适用于数字信号的传输。 
    2. 数据链路层：数据链路层是建立在物理传输能力的基础上，以帧为单位传输数据，它的主要任务就是进行数据封装和数据链接的建立。封装的数据信息中，地址段含有发送节点和接收节点的地址，控制段用来表示数据连接帧的类型，数据段包含实际要传输的数据，差错控制段用来检测传输中帧出现的错误。  具体讲，数据链路层的功能包括：数据链路连接的建立与释放、构成数据链路数据单元、数据链路连接的分裂、定界与同步、顺序和流量控制和差错的检测和恢复等方面。  
    3. 网络层：网络层属于OSI中的较高层次了，从它的名字可以看出，它解决的是网络与网络之间，即网际的通信问题，而不是同一网段内部的事。网络层的主要功能即是提供路由，即选择到达目标主机的最佳路径，并沿该路径传送数据包。除此之外，网络层还要能够消除网络拥挤，具有流量控制和拥挤控制的能力。网络边界中的路由器就工作在这个层次上，现在较高档的交换机也可直接工作在这个层次上，因此它们也提供了路由功能，俗称“第三层交换机”。网络层的功能包括：建立和拆除网络连接、路径选择和中继、网络连接多路复用、分段和组块、服务选择和流量控制。
    4. 传输层：传输层解决的是数据在网络之间的传输质量问题，它属于较高层次。传输层用于提高网络层服务质量，提供可靠的端到端的数据传输，如常说的QoS就是这一层的主要服务。这一层主要涉及的是网络传输协议，它提供的是一套网络数据传输标准，如TCP协议.传输层的功能包括：映像传输地址到网络地址、多路复用与分割、传输连接的建立与释放、分段与重新组装、组块与分块。

    5. 会话层：会话层利用传输层来提供会话服务，会话可能是一个用户通过网络登录到一个主机，或一个正在建立的用于传输文件的会话.会话层的功能主要有：会话连接到传输连接的映射、数据传送、会话连接的恢复和释放、会话管理、令牌管理和活动管理。
    6. 表示层：表示层用于数据管理的表示方式，如用于文本文件的ASCII和EBCDIC，用于表示数字的1S或2S补码表示形式。如果通信双方用不同的数据表示方法，他们就不能互相理解。表示层就是用于屏蔽这种不同之处。  表示层的功能主要有：数据语法转换、语法表示、表示连接管理、数据加密和数据压缩。  

    7. 应用层：这是OSI参考模型的最高层，它解决的也是最高层次，即程序应用过程中的问题，它直接面对用户的具体应用。应用层包含用户应用程序执行通信任务所需要的协议和功能，如电子邮件和文件传输等，在这一层中TCP/IP协议中的FTP、SMTP、POP等协议得到了充分应用。 

4.了解通信网络中的安全属性
    1. 可用性:
    指得到授权的实体在需要时可以使用所需要的网络资源和服务。用户对信息和通信需求是随机的多方面的，有的还对实时性有较高的要求。网络必须能够保证所有用户的通信需要，不能拒绝用户要求。攻击者常会采用一些手段来占用或破坏系统的资源，以阻止合法用户使用网络资源，这就是对网络可用性的攻击。对于针对网络可用性的攻击，一方面要采取物理加固技术，保障物理设备安全、可靠地工作；另一方面通过访问控制机制，阻止非法访问进入网络。
     2. 机密性:
     指网络中信息不被非授权实体(包括用户和进程等)获取与使用。包括国家机密、企业和社会团体的商业和工作秘密，个人秘密(如银行账号)和隐私(如邮件、浏览习惯)等。网络的广泛使用，使对网络机密性的要求提高了。网络机密性主要是密码技术，网络不同层次上有不同的机制来保障机密性。物理层主要是采取屏蔽技术、干扰及跳频技术防止电磁辐射造成信息外泄：在网络层、传输层及应用层主要采用加密、路由控制、访问控制、审计等方法 

      3. 完整性:
      指网络信息的真实可信性，即网络少的信息不会被偶然或者蓄意地进行删除、修改、伪造、插入等破坏，保证授权用户得到的信息是真实的。只有具有修改权限的实体才能修改信息，如果信息被未经授权的实体修改了或在传输过程中出现厂错误，信息的使用者应能够通过一定的方式判断出信息是否真实可靠。 

      4. 可靠性:
      是指系统在规定的条件下和规定的时间内，完成规定功能的概率。可靠性是网络安全最基本的要求之一。目前对于网络可靠性的研究主要偏重于硬件可靠性的研究，主要采用硬件冗余、提高研究质量和精确度等方法。实际上软件的可靠性、人员的可靠性和环境的可靠性在保证系统可靠性方面也是非常重要的。 
      5. 不可抵赖性，也称为不可否认性；
      是指通信的双方在通信过程中，对于自己所发送或接收的消息不可抵赖：即发送者不能抵赖他发送过消息的事实和消息内容，而接收者也不能抵赖其接收到消息的事实和内容


5.了解通信网络应用分类/6.了解“网络”习惯分类(*这两个的答案可以放在一起*)
   1. 按 *传输介质* 可分为无线通信网与有线通信网：
无线通信网是指传输介质为自由空间，例如无线电波、红外、激光等无线方式，常见的形式有微波通信网、短波通信网、移动通信网与卫星通信网等。有限通信网则是指介质为导线、光缆、电缆等通信形式，进一步可分为载波通信网与光纤通信网等。

   2. 按 *技术* 分类有PDH技术、SDH技术、DWDM技术、CDMA移动技术、ATM网络技术、FR（帧中继）等通信系统：
PDH与SDH分别指准同步数字体系和同步数字体系，可用于光纤通信网、微波通信网和卫星通信网；DWDM通信系统是指采用密集波分复用技术在光纤上实现的大容量传输网，目前主要用于长途光纤通信网；CDMA移动通信网是指采用码分多址（CDMA）方式实现移动通信网，目前在第二代移动通信中的IS-95标准和第三代移动通信的全部标准都采用CDMA方式；ATM网络和帧中继FR网分别是指采用信元中继技术得异步转移模式ATM和快速帧中继FR技术实现的快速交换网，可用于城域网和广域网。

   3. 按 *业务* 分类可分为电报网、电话网、数据网和因特网等。电报网网还可分为有线电报网与无线电报网；电话网可再分为固定电话网、移动电话网与长途电话网；数据网则可分为窄带数据和宽带数据。
   4. 按 *地域* 分类可分为局域网（LAN）、城域网（MAN）和广域网（WAN），计算机网络常采用此种分类方法：
所谓局域网是指传输覆盖区从家庭、办公室、建筑物到园区，分布局域从几百米到几公里的通信网络，常用的有办公室网和校园网等；
城域网是指传输覆盖区以城市为主，分布区域从几百到几十公里，介于WAN与LAN之间，地理范围局限于城市的宽带通信网络，以高速、大容量宽带方式实现城域内LAN的互联和用户的宽带接入业务，例如电信运营商在各城市建立的宽带骨干网；
广域网则是指传输覆盖区为省、国家甚至全球，分布从几百到几万公里，采用大容量长途传输技术，把各个城域网连接起来，例如全球最大的广域网因特网。

   5. 按 *属性* 分类可分为公用网和专用网：
公用网是由电信部门经营和管理的固定或无线网络，通过公用用户网络接口连接各专用网和用户终端。例如目前常用的公用电话网和公用数据网。
专用网是指一个单位或部门范围内的网络，由于它的网络规模比公用网要小，而且有的也不需要记费等管理规程，因此很多新的网络设备和技术也往往先在专用网中使用，通常也能够提供高质量的多媒体业务和高速数据传输。目前专用网主要是以太网，还有ATM及各种无线技术。例如常用的单位内部电话网和计算机局域网。

7.了解通信网络安全问题本质成因
  计算机通信网络安全涉及许多学科，例如，网络技术，通信技术，信息安全技术，计算机科学等，其主要功能是为网络硬件和软件系统，并有很好的保护数据的系统，确保它不会受到任何不良因素的伤害，从而使网络系统的连续及平滑的操作中，网络服务畅通无阻。 
  - 计算机通信网络安全的影响客观原因 
      　一方面，因为与联结特性的通信网络的计算中广泛，因此，在很大的程度上，提供了网络攻击一定条件下，非法人员会使用网络安全缺陷存在的硬件和软件的网络系统上，并在系统中严重的攻击数据，即使有些信息安全的保护措施，但还是很容易泄漏。其次，由于在计算机系统和通信网络本身容易受到损伤，所以，在不同程度的攻击是难以避免的，虽然，在为了防止大型软件系统，比如在使用微软的操作系统的安全问题过程，并制定了多种方案来解决问题，但程序不能完美，但仍存在一些安全隐患。此外，由于计算机病毒的传播，因此，由严重的攻击中不同程度的网络系统中，数据或改变，或破坏，从而导致整个系统的故障;再次，目前，通信网络系统中经常使用的电子商业软件，但电子商务软件的源代码是开放的这是无法避免的，安全问题存在的软件，所有广为人知。 
  - 计算机通信网络安全的影响主观原因
      主要是因为计算机系统和网络管理人员无视安全隐患，有实际操作的技术水平不高，在操作中往往违反该制剂的安全要求，操作规则是不是解决办法，例如，在该着作公开发表，因为长时间使用一个密钥对一些未公开的秘密文件，密码是各种因素，如裂缝，最终导致网络系统失去了理性和大量的管理漏洞。在网络系统管理和使用过程中，人们会更偏向的福利和人力管理方便，为小安全问题需要考虑。
      综上所述，为了保证计算机通信网络的安全性，网民广大共同完成，他们不仅具备计算机通信网络安全技术有全面的掌握，还要熟悉各方面的知识，不只有有法律意识强，而且还具备良好的道德品质和良好的技术安全风险的级别存在，只有这样，网络降低了，它会平稳运行。

***** 2.通信协议及应用*
1. 熟悉OSI七层模型
   OSI模型由7个层组成，层层堆积：物理层、数据链路层、网络层、传输层、会话层、表示层和应用层。每一层都处理某特定的通信任务，使用基于协议的通信来与协议栈的下一层交换数据。两个网络设备间的通信就是通过在每一设备的协议栈中上上下下来完成的。例如，有一工作站要与一服务器进行通信，任务从工作站的应用层开始，经由较低的层格式化某类信息，直至数据到达物理层，然后通过网络传输到服务器。服务器于协议栈的物理层获取信息，向上层发送信息以解释信息，直到到达应用层。每一层可用其名称称呼，也可用其在协议栈中的位置表明。例如，最底层可称为物理层或第1层。

   最底层执行的功能与物理通信相关，如构建帧、传输含有包的信号;中间层协调结点间的网络通信，如确保通信会话无中断、无差错地持续进行。最高层的工作直接影响软件应用和数据表示，包括数据格式化、加密以及数据与文件传输管理。总括起来，这些层称为协议栈。
 
2. 熟悉TCP/IP协议族的基本协议及TCP/IP协议族存在的固有安全问题.
   1. TCP/IP协议簇的基本协议
| 层         | 协议                                                                       |
|------------+----------------------------------------------------------------------------|
| 应用层     | HTTP、SMTP、SNMP、FTP、Telnet、SIP、SSH、NFS、RTSP、XMPP、Whois、ENRP      |
| 表示层     | XDR、ASN.1、SMB、AFP、NCP                                                  |
| 会话层     | ASAP、SSH、ISO 8327 / CCITT X.225、RPC、NetBIOS、ASP、Winsock、BSD sockets |
| 传输层     | TCP、UDP、TLS、RTP、SCTP、SPX、ATP、IL                                     |
| 网络层     | IP、ICMP、IGMP、IPX、BGP、OSPF、RIP、IGRP、EIGRP、ARP、RARP、X.25          |
| 数据链路层 | 以太网、令牌环、HDLC、帧中继、ISDN、ATM、IEEE 802.11、FDDI、PPP            |
| 实体层     | 线路、无线电、光纤                                                         |
 


   2. TCP/IP协议的安全隐患
   造成操作系统漏洞的一个重要原因，就是协议本身的缺陷给系统带来的攻击点。网络协议是计算机之间为了互联共同遵守的规则。目前的互联网络所采用的主流协议TCP/IP，由于在其设计初期人们过分强调其开发性和便利性，没有仔细考虑其安全性，因此很多的网络协议都存在严重的安全漏洞，给Internet留下了许多安全隐患。另外，有些网络协议缺陷造成的安全漏洞还会被黑客直接用来攻击受害者系统。本文就TCP/IP协议自身所存在的安全问题和协议守护进程进行了详细讨论，指出针对这些安全隐患的攻击。
   3.  TCP协议的安全问题
   TCP使用三次握手机制来建立一条连接，握手的第一个报文为SYN包；第二个报文为SYN/ACK包，表明它应答第一个SYN包同时继续握手的过程；第三个报文仅仅是一个应答，表示为ACK包。若A放为连接方，B为响应方，其间可能的威胁有：
       1. 攻击者监听B方发出的SYN/ACK报文。
       2. 攻击者向B方发送RST包，接着发送SYN包，假冒A方发起新的连接。
       3. B方响应新连接，并发送连接响应报文SYN/ACK。
       4. 攻击者再假冒A方对B方发送ACK包。
   这样攻击者便达到了破坏连接的作用，若攻击者再趁机插入有害数据包，则后果更严重。
   TCP协议把通过连接而传输的数据看成是字节流，用一个32位整数对传送的字节编号。初始序列号（ISN）在TCP握手时产生，产生机制与协议实现有关。攻击者只要向目标主机发送一个连接请求，即可获得上次连接的ISN，再通过多次测量来回传输路径，得到进攻主机到目标主机之间数据包传送的来回时间RTT。已知上次连接的ISN和RTT，很容易就能预测下一次连接的ISN。若攻击者假冒信任主机向目标主机发出TCP连接，并预测到目标主机的TCP序列号，攻击者就能伪造有害数据包，使之被目标主机接受。
   4. IP协议的安全问题
   IP协议在互连网络之间提供无连接的数据包传输。IP协议根据IP头中的目的地址项来发送IP数据包。也就是说，IP路由IP包时，对IP头中提供的源地址不作任何检查，并且认为IP头中的源地址即为发送该包的机器的IP地址。这样，许多依靠IP源地址做确认的服务将产生问题并且会被非法入侵。其中最重要的就是利用IP欺骗引起的各种攻击。
   以防火墙为例，一些网络的防火墙只允许网络信任的IP数据包通过。但是由于IP地址不检测IP数据包中的IP源地址是否为放送该包的源主机的真实地址，攻击者可以采用IP源地址欺骗的方法来绕过这种防火墙。另外有一些以IP地址作为安全权限分配依据的网络应用，攻击者很容易使用IP源地址欺骗的方法获得特权，从而给被攻击者造成严重的损失。事实上，每一个攻击者都可以利用IP不检验IP头源地址的特点，自己填入伪造的IP地址来进行攻击，使自己不被发现。


   5. TCP/IP协议安全问题的防范
   TCP协议安全问题的防范
   对于SYN Flood攻击，目前还没有完全有效的方法，但可以从以下几个方面加以防范：
      1. 对系统设定相应的内核参数，使得系统强制对超时的SYN请求连接数据包的复位，同时通过缩短超时常数和加长等候队列使得系统能迅速处理无效的SYN请求数据包。
      2. 建议在该网段的路由器上做些配置的调整，这些调整包括限制SYN半开数据包的流量和个数。
      3. 建议在路由器的前端多必要的TCP拦截，使得只有完成TCP三次握手过程的数据包才可以进入该网段，这样可以有效的保护本网段内的服务器不受此类攻击。
   6. IP协议安全问题的防范
      1. 抛弃基于地址的信任策略。这是最简单的方法。
      2. 进行包过滤。如果网络是通过路由器接入Internet的，那么可以利用路由器来进行包过滤。确认只有内部LAN可以使用信任关系，而内部LAN上的主机对于LAN以外的主机要慎重处理。路由器可以过滤掉所有来自于外部而希望与内部建立连接的请求。
      3. 使用加密技术。阻止IP欺骗的一种简单的方法是在通信时要求加密传输和验证。当有多种手段并存时，加密方法可能最为适用。 
   7. TCP/IP各层的安全性和提高各层安全性的方法
      1. 网络层的安全性
      在过去的十年里，已经提出了一些方案对网络层的安全协议进行标准化。例如，安全协议3号（SP3）就是美国国家安全局以及标准技术协会作为安全数据网络系统（SDNS）的一部分而制定的。网络层安全协议（NLSP）是由国际标准化组织为无连接网络协议（CLNP）制定的安全协议标准。集成化NLSP（I-NLSP）是由美国国家科技研究所提出的包括IP和CLNP在内的统一安全机制。SWIPE是另一个网络层的安全协议，由Ioannidis和Blaze提出并实现原型。所有这些提案的共同点多于不同点。事实上，他们用的都是IP封装技术。其本质是，纯文本的包被加密，封装在外层的IP报头里，用来对加密的包进行Internet上的路由选择。到达另一端时，外层的IP报头被拆开，报文被解密，然后送到收报地点。
      网络安全性的主要优点是它的透明性，也就是说，安全服务的提供不需要应用程序、其他通信层次和网络部件做任何改动。它最主要的缺点是：网络层一般属于不间进程和相应条例的包不做区别。对所有去往同一地址的包，它将按照同样的加密密钥和访问控制策略来处理。这可能导致提供不了所需要的功能，也会导致性能下降。针对面向主机的密钥分配的这些问题，RFC 1825允许（甚至可以说是推荐）使用面向用户的密钥分配，其中，不同的连接会得到不同的加密密钥。但是，面向用户的密钥分配需要对相应的操作系统内核作比较大的改动。
      简而言之，网络层是非常适合提供基于主机对主机的安全服务的。相应的安全协议可以用来在Internet上建立安全的IP通道和虚拟私有网。例如，利用它对IP包的加密和解密功能，可以简捷地强化防火墙系统的防卫能力。RSA数据安全公司已经发起了一个倡议，来推进多家防火墙和TCP/IP软件厂商联合开发虚拟私有网，该倡议被称为S-WAN（安全广域网）倡议，其目标是制定和推荐网络层的安全协议标准。
      2. 传输层的安全性
         在网络应用编程中，通常使用广义的进程间通信（IPC）机制来与不同层次的安全协议打交道。在Internet中提供安全服务的首先一个想法便是强化它的IPC界面，如BSD、Sockets等，具体做法包括双端实体的认证，数据加密密钥的交换等。Netscape通信公司遵循了这个思路，制定了建立在可靠的传输服务（如TCP/IP所提供）基础上的安全接层协议（SSL）。
         网络安全机制的主要优点是它的透明性，即安全服务的提供不要求应用层做任何改变。这对传输层来是说是做不到的。原则上，任何TCP/IP应用，只要应用传输层安全协议，比如说SSL或IPC，就必定要进行若干修改以增加相应的功能，并使用不同的IPC界面。于是，传输层安全机制的主要缺点就是要对传输层IPC界面和应用程序两端都进行修改。可是，比起Internet层和应用层的安全机制来，这里修改还是相当小的。另一个缺点是，基于UDP的通信很难在传输层建立起安全机制来。同网络层安全机制相比，传输层安全机制的主要优点是它提供基于进程对进程的（而不是主机对主机的）安全服务。这一成就如果再加上应用级的安全服务，就可以再向前跨越一大步了。
       3. 应用层的安全性
         网络层的安全协议允许为主机（进程）之间的数据通道增加安全属性，这以为着真正的数据通道还是建立在主机（或进程）之间，但却不可能区分在同一通道上传输的一个具体文件的安全性要求。比如说，如果一个主机与另一个主机之间建立起一条安全的IP通道，那么所有在这条通道上传输的IP包就到要自动的被加密。同样，如果一个进程和另一个进程之间通过传输层安全协议建立起了一条安全的数据通道，那么两个进程间传输的所有消息就都要自动的被加密。
         一般来说，在应用层提供安全服务有几种可能的做法，一个是对每个应用（及应用协议）分别进行修改。一些重要的TCP/IP应用已经这样做了。在RFC1421至1424中，IETF规定了私用强化邮件（PEM）来为基于SMTP的电子邮件系统提供安全服务。Internet业界采纳PEM的步子太慢的原因是PEM依赖于一个既存的、完全可操作的PKI（公钥基础结构）。建立一个符合PEM规范的PKI需要多方在一个共同点上达成信任。作为一个中间步骤，Phil Zimmermann开发了一个软件包，叫做PGP（Pretty Good Privacy）。PGP符合PEM的绝大多数规范，但不必要求PKI的存在。相反，它采用了分布式的信任模型，即由每个用户自己决定该信任哪些其他用户。因此，PGP不是去推广一个全局的PKI，而是让用户自己建立自己的信任之网。
     

 总结：
      总起来说，TCP/IP安全性的进展实际上与ICA思想的安全保证是有所协同与汇聚的，比起防火墙等措施来已更上一层楼。因此，基于TCP/IP协议的安全计算问题应以科学求实、积极创新的原则而努力推进，决不能不求创新，甚至悲观失望。


3. 熟悉IPv6,移动互联网等技术及应用
IPv6二进位制下为128位长度，以16位为一组，每组以冒号":"隔开，可以分为8组，每组以4位十六进制方式表示。例如：
2001:0db8:85a3:08d3:1319:8a2e:0370:7344
是一个合法的IPv6地址。
同时IPv6在某些条件下可以省略，以下是省略规则
规则1：每项数字前导的0可以省略，省略后前导数字仍是0则继续，例如下组IPv6是相等的。
2001:0DB8:02de:0000:0000:0000:0000:0e13
2001:DB8:2de:0000:0000:0000:0000:e13
2001:DB8:2de:000:000:000:000:e13
2001:DB8:2de:00:00:00:00:e13
2001:DB8:2de:0:0:0:0:e13
规则2：可以用双冒号"::"表示一组0或多组连续的0，但只能出现一次。
例如
1. 如果四组数字都是零，可以被省略。遵照以上省略规则，下面这两组IPv6都是相等的。
1-1.
2001:DB8:2de:0:0:0:0:e13
2001:DB8:2de::e13
1-2.
2001:0DB8:0000:0000:0000:0000:1428:57ab
2001:0DB8:0000:0000:0000::1428:57ab
2001:0DB8:0:0:0:0:1428:57ab
2001:0DB8:0::0:1428:57ab
2001:0DB8::1428:57ab
2.不过请注意有的情形下省略是非法的，因为双冒号出现两次，所以这个IPv6是非法的。
2001::25de::cade
因为它有可能是下种情形之一，造成无法推断。
2001:0000:0000:0000:0000:25de:0000:cade
2001:0000:0000:0000:25de:0000:0000:cade
2001:0000:0000:25de:0000:0000:0000:cade
2001:0000:25de:0000:0000:0000:0000:cade
3.如果这个地址实际上是IPv4的地址，后32位可以用10进制数表示；因此：
::ffff:192.168.89.9相等於::ffff:c0a8:5909，但不等於::192.168.89.9和::c0a8:5909。
::ffff:1.2.3.4格式叫做IPv4映射位址。而::1.2.3.4格式叫做IPv4一致位址，目前已被取消。
IPv4位址可以很容易的转化为IPv6格式。举例来说，如果IPv4的一个地址为135.75.43.52（十六进制为0x874B2B34），它可以被转化为0000:0000:0000:0000:0000:ffff:874B:2B34或者::ffff:874B:2B34。同时，还可以使用混合符号（IPv4-compatible address），则地址可以为::ffff:135.75.43.52。
   
4. 了解典型的通信网络及设备.
    有线通信
概述
有线通信是指通信设备传输间需要经过线缆连接，即利用架空线缆、同轴线缆、光纤、音频线缆等传输介质传输信息方式。
优点与缺点
有线通信设备最大优势就是抗干扰性强，稳定性高，具备一定的保密性，传输速率快，带宽能够无限大；但有线通信受环境影响较大，扩展性较弱，有衰减，施工难度大，移动性差，费用高。
有线通信设备
常用的有线通信设备有：电脑、 电视、电话、PCM、光端机等。
无线通信编辑
概述
无线通信是指不需要物理连接线的通信，即利用电磁波信号可以在自由空间中传播的特征进行信息交换的一种通信方式。
优点与缺点
无线通信设备最大优点就是环境，不需要受线的限制，具有一定的移动性，可以在移动状态下通过无线连接进行通信，施工难度低，成本低；但无线通信设备抗干扰较弱，传输速率较慢，带宽有限，传输距离也有限制，费用低。但是无线通信正在改变相应的技术让传输速率更高（802,11n的速率能到达100Mbps不低于有线通信），更稳定方便，所以无线通信设备将是发展趋势。
无线通信设备
卫星、无线电台、无线电视（公交车或地铁上）、无线局域网、移动电话（手机）、手机GPRS上网等。
车载设备编辑有线通信
概述
有线通信是指通信设备传输间需要经过线缆连接，即利用架空线缆、同轴线缆、光纤、音频线缆等传输介质传输信息方式。
优点与缺点
有线通信设备最大优势就是抗干扰性强，稳定性高，具备一定的保密性，传输速率快，带宽能够无限大；但有线通信受环境影响较大，扩展性较弱，有衰减，施工难度大，移动性差，费用高。
有线通信设备
常用的有线通信设备有：电脑、 电视、电话、PCM、光端机等。
无线通信编辑
概述
无线通信是指不需要物理连接线的通信，即利用电磁波信号可以在自由空间中传播的特征进行信息交换的一种通信方式。
优点与缺点
无线通信设备最大优点就是环境，不需要
车载终端是用于车辆定位服务一种车载设备。它能为车辆用户提供定位、导航、防盗、防抢劫、信息发布、上网、游戏及多媒体等服务一种车载设备。
广泛适用于：公安、医疗（120救护）、汽车租赁、出租车调度、长途客运货运和私人需要车辆安全监控等方面。
组成部分
由GPS模块、GSM模块、控制模块及外围设备等组成。
GPS模块接收通信导航卫星定位信息，经控制模块运算解析后，发送到GSM模块，GSM模块GPRS功能将运算解析后数据，GPS服务平台进一步运算解析后，变成人们能够读懂信息，人们再这些信息，对车辆进行调度、管理和控制。所有数据通信链路均为双向。
主要功能
1、定位功能：GPS实现卫星定位后，终端液晶显示器上显示经纬度、速度、方位、海拔高度，并以GPRS或GSM将监控目标以上数据发回监控中心；
2、自导航功能：自带显示器显示目标经度、纬度、高度、速度，接收中心导航信息；
3、遇劫报警功能：遇到车匪路霸时，启动隐蔽安装驾驶室内报警按钮，车载系统就会自动向监控中心发送报警信号，直至收到监控中心应答为止；
4、跟踪功能：车辆被盗、抢劫后，监控中心能自动跟踪报警车辆；
5、发送状态功能：按数字键，即可向监控中心发送事先编写好状态（路阻、故障、事故求助、拨打电话 等）；
6、文本转语音功能：监控中心发送调度指令、短信，终端会用女声自动读出；(选配)
7、遥控熄火功能：对被劫持车辆进行营救过程中，中心可以营救需要遥控车辆强行熄火，系统设有双保险，设备故障不会造成意外熄火；
8、越界报警功能：系统可预先设置车辆行驶范围，超出该范围系统会自动向中心报警，车辆自动语音提示和图标显示越界；
9、超速报警功能：系统可预先设置车辆行驶速度，超出该速度范围系统自动向中心报警，系统自动生成统计报表；
10、行驶轨迹记录功能：自动记录车辆行驶数据，该数据记录终端内部FLASH储存器里面，遇到意外掉电时数据不会丢失。

***** 3.安全通信协议*
1. 了解典型的安全通信协议.

2. 了解典型的安全通信协议在通信过程中的应用.

* 典型例题(答案仅供参考,不保证正确)
** 单项
例:过程是指 (b)。
a) 有输入和输出的任意活动
b) 通过使用资源和管理,将输入转化为输出的任意活动
c) 所有业务活动的集合
d) 以上都不对
** 多项
例:防火墙的基本类型有 (a, b)。
a) 包过滤防火墙
b) 应用层网关
c) 电路网关
d) 混合器型防火墙

** 综合题
例:某物流公司(上百名员工)在年初发生一起严重泄密事件:某员工因对公司不满,在离职半年后将其在职期间窃取的员工工资表(该表以 excel 文档保存在人事经理主机上)以匿名邮件的形式发给公司里每个人,公司内部震动很大,一些不满薪金制度的员工还递上了辞呈。IT 主管于是从网上下载一个文档加密软件提交予人事部,要求其将相关重要文档加密存放。

请就上述事件指出该物流公司在信息安全防护措施方面具有哪些问题(至少列出四点),并为防止类似事件发生给出一个整体安全集成解决方案。
*答案*

